language: ruby
cache: bundler
before_install:
  - gem install bundler
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O /tmp/phantomjs.tar.bz2
  - tar -vxjf /tmp/phantomjs.tar.bz2
  - export PATH=$PWD:$PATH
rvm:
  - 2.1
  - 2.0
  - 1.9.3
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
  fast_finish: true
